export const UserDataTypes = {
  SET_USER_DATA: "SET_USER_DATA",
  SET_IS_SUBSCRIBED: "SET_IS_SUBSCRIBED",
  SET_COMPARED_PRODUCTS: "SET_COMPARED_PRODUCTS",
  SET_COMPARED_PRODUCTS_VIEW: "SET_COMPARED_PRODUCTS_VIEW",
};
